### ISSUE TITLE
Settings Not Detecting Playnite Desktop App, only Full Screen App

### ISSUE THREAD

**Issue by azw131** [toonymak1993/GamingConsoleMode#1]
The desktop app for Playnite is not a selectable option during settings configuration, only the Fullscreen App is. The Desktop App is the version that matters most, as it contains the authentication for GamePass etc. When booting directly into Fullscreen without desktop opening, games from gamepass, steam, etc. refuse to launch and throw an error code.

**Comment by azw131** [comment]
Update: The third option "Choose Another Launcher" allows me to see/select the Playnite Desktop App. I have things working now. It would likely be worth having the designated 'Playnite' selection updated to allow for this though, so as to avoid confusion. Thank you for putting this software together, it's great on the Ally X.

**Comment by Kosnix** [comment]
Hello, this is quite normal. The goal is to use the full-screen interface of playnite, hence the purple icon chosen for the illustration. I have voluntarily limited the choices to avoid confusion between the executables.
Thanks for your feedback.
